apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/crds.yaml
  - manifests/operator.yaml
  - manifests/elasticsearch.yaml
  - manifests/kibana.yaml
  - manifests/logstash.yaml
  - manifests/filebeat.yaml
